<!--
created by hafsa
-->
<template>
<page-section>
  <template #heading>
    <span>{{ $t('title') }}</span>
    <button id="form-list-create-button" type="button" 
            class="btn btn-primary" @click="createModal.show(0)">
      <span class="icon-plus-circle"></span>{{ $t('action.create') }}&hellip;
    </button>
    <form-sort v-model="sortMode"/>
  </template>
  <template #body>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Created At</th>
          <th>Updated At</th>
        </tr>
      </thead>
      <tbody>
        <tr class="form-row" v-for="form of allForms" :key="form.xmlFormId">
          {{ console.log('form', form) }}
          <td class="name">
            <link-if-can :to="primaryFormPath2(form)">
              {{ form.xmlFormId}}
            </link-if-can>
          </td>
          <td class="created-at">{{ form.createdAt }}</td>
          <td class="updated-at">{{ form.updatedAt }}</td>
        </tr>
      </tbody>
    </table>
  </template>
</page-section>
<form-new v-bind="createModal" @hide="createModal.hide()"
      @success="afterCreate"/>
</template>

<script>
import FormNew from './new.vue';
import { useRequestData } from '../../request-data';
import { apiPaths } from '../../util/request';
import { noop } from '../../util/util';
import LinkIfCan from '../link-if-can.vue';
import useRoutes from '../../composables/routes';
import PageSection from '../page/section.vue';
import FormSort from './sort.vue';
import sortFunctions from '../../util/sort';
import { modalData } from '../../util/reactivity';

export default {
  name: 'AllForms',
  components: { LinkIfCan, PageSection, FormSort, FormNew },
  setup(){
    const {allForms} = useRequestData();
    const { formPath, primaryFormPath2 } = useRoutes();
    

    const fetchAllForms = () => {
      allForms.request({
        url: apiPaths.allForms(),
        extended: true,
      }).catch(noop);
    };
    fetchAllForms();

    return {
      allForms,formPath, 
      primaryFormPath2,};
  },
  data() {
    return {
      createModal: modalData(),
      sortMode: 'alphabetical'
    };
  },
  computed: {
    sortFunction() {
      return sortFunctions[this.sortMode];
    }
  },
  methods: {
    //change this
    afterCreate(form) {
      const message = this.$t('alert.create', {
        name: form.name != null ? form.name : form.xmlFormId
      });
      this.$router.push(this.formPath(form.projectId, form.xmlFormId, 'draft'))
        .then(() => { this.alert.success(message); });
    }
  }
};
</script>

<style lang="scss">
template {
  width: 100%;
}
table {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 14px;
  line-height: 1.42857143;
  width: 100%;
}
table thead tr th {
    border-bottom: 1px solid #bbb;
    font-size: 12px;
    padding: 8px 9px 6px;
    vertical-align: bottom;
    line-height: 1.42857143;
    text-align: left;
}
tbody{
width: 100%;
vertical-align: middle; 
}
.form-row{
  td{
    font-size: 16px;
    padding: 4px 0px 4px 6px;
    color: #333;
  }
  .updated-at, .created-at {
    text-align: right;
    padding-right: 10px;
    width: 80px;

  & [class*='icon'] {
    margin-left: 5px;
    color: #888;
  }
}
}

.name {
  font-size: 18px;
}

</style>

<i18n lang="json5">
  {
    "en": {
      // This is a title shown above a section of the page.
      "title": "Forms",
      "action": {
        // This is the text of a button that is used to create a new Form.
        "create": "New"
      },
      "emptyTable": "There are no Forms to show.",
      "alert": {
        "create": "Your new Form “{name}” has been created as a Draft. Take a look at the checklist below, and when you feel it’s ready, you can publish the Form for use."
      }
    }
  }
  </i18n>
<!-- Autogenerated by destructure.js -->
  <i18n>
    {
      "cs": {
        "title": "Formuláře",
        "action": {
          "create": "Nový"
        },
        "emptyTable": "Nejsou k dispozici žádné formuláře.",
        "alert": {
          "create": "Váš nový formulář „{name}“ byl vytvořen jako koncept. Podívejte se na odškrtávací seznam níže a až budete mít pocit, že je připraven, můžete formulář publikovat k použití."
        }
      },
      "de": {
        "title": "Formulare",
        "action": {
          "create": "Neu"
        },
        "emptyTable": "Keine Formulare zum Anzeigen vorhanden.",
        "alert": {
          "create": "Ihr neues Formular \"{name}\" wurde als Entwurf erstellt. Überprüfen Sie die Checkliste unten: Wenn Sie finden, das sie abgearbeitet ist, können sie das Formular veröffentlichen."
        }
      },
      "es": {
        "title": "Formularios",
        "action": {
          "create": "Nuevo"
        },
        "emptyTable": "No hay formularios para mostrar.",
        "alert": {
          "create": "Su nuevo formulario \"{name}\" se ha creado como un borrador. De un vistazo a la lista de verificación a continuación, y cuando sienta que está lista, puede publicar el formulario para su uso."
        }
      },
      "fr": {
        "title": "Formulaires",
        "action": {
          "create": "Nouveau"
        },
        "emptyTable": "Il n'y a pas de formulaire à montrer.",
        "alert": {
          "create": "Votre nouveau formulaire \"{name}\" a été créé en tant qu'ébauche. Jetez un œil à la liste de contrôle ci-dessous, et quand vous pensez que c'est prêt, vous pouvez publier le formulaire pour utilisation."
        }
      },
      "id": {
        "title": "Formulir",
        "action": {
          "create": "Formulir Baru"
        },
        "emptyTable": "Tidak ada formulir untuk ditampilkan.",
        "alert": {
          "create": "Formulir {name} telah berhasil disimpan sebagai draf. Lihatlah daftar periksa di bawah, dan ketika Anda merasa sudah siap, Anda dapat menerbitkan formulir untuk digunakan."
        }
      },
      "it": {
        "title": "Formulari",
        "action": {
          "create": "Nuovo"
        },
        "emptyTable": "Non ci sono formulari da mostrare.",
        "alert": {
          "create": "Il tuo nuovo formulario\"{name}\" è stato creato come bozza. Dai un'occhiata alla lista di controllo qui sotto e quando ritieni che sia pronto, puoi pubblicare il formulario per l'uso."
        }
      },
      "ja": {
        "title": "フォーム",
        "action": {
          "create": "新規作成"
        },
        "emptyTable": "表示できるフォームはありません。",
        "alert": {
          "create": "新規フォーム\"{name}\"が下書きとして作成されました。以下のチェックリストを参考にして、準備が整ったらフォームを公開して使用できます。"
        }
      },
      "sw": {
        "title": "Fomu",
        "action": {
          "create": "Mpya"
        },
        "emptyTable": "hakuna Fomu za kuonyesha",
        "alert": {
          "create": "Fomu yako mpya \"{name}\" imeundwa kama Rasimu. Angalia orodha hapa chini, na unapohisi iko tayari, unaweza kuchapisha Fomu kwa matumizi."
        }
      }
    }
    </i18n>
    